services:

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www
    networks:
      - network

  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb/
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - network
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    build: ./requirements/wordpress/
    image: wordpress
    volumes:
      - wordpress:/var/www
    networks:
      - network
    env_file:
      - .env

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mbenicho/data/wordpress_volume'
  database:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mbenicho/data/database_volume'

networks:
  network:
    driver: bridge
